[build]
HUGO_VERSION = "0.77.0"
HUGO_THEME = "repo"
GO_VERSION = "1.16.2"
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir=../.. --baseURL $URL"

[context.deploy-preview]
command = "cd exampleSite &&  hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
