[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir=../.. --baseURL $URL"

[context.production.environment]
HUGO_VERSION = "0.73.0"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "cd exampleSite &&  hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.73.0"
HUGO_THEME = "repo"
